services:
  springboot-api:
    build: ./
    environment:
      - SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI:-mongodb+srv://sachintha:tfeZO9gyWdb2PotC@cluster0.kgzqpei.mongodb.net/currency_db?appName=Cluster0}
    ports:
      - "8084:8084"
    expose:
      - "8084"

  node-client:
    build: ./UI
    environment:
      - API_BASE_URL=http://springboot-api:8084
    ports:
      - "3000:3000"
    depends_on:
      - springboot-api