services:
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  springboot-api:
    build: ./
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/currency_db
    expose:
      - "8084"
    depends_on:
      - mongodb

  node-client:
    build: ./UI
    environment:
      - API_BASE_URL=http://springboot-api:8084
    ports:
      - "3000:3000"
    depends_on:
      - springboot-api

volumes:
  mongo-data: