spring.data.mongodb.uri=mongodb://localhost:27017/currency_db
#spring.data.mongodb.uri=mongodb://mongodb:27017/currency_db
server.port=8084
app.security.default-api-key=${SPRING_API_KEY:SUPER-SECRET-DEV-KEY-123}
app.security.default-client-name=ui-dev-client